export type Direction = "h" | "v";

export type Leaf = {
  kind: "leaf";
  id: string;
  command?: string;
};

export type Split = {
  kind: "split";
  id: string;
  direction: Direction;
  ratio: number;
  a: Pane;
  b: Pane;
};

export type Pane = Leaf | Split;

let idCounter = 0;
export const nextId = () => `p${++idCounter}`;

export const makeLeaf = (command?: string): Leaf => ({
  kind: "leaf",
  id: nextId(),
  command,
});

export const initialTree = (): Pane => makeLeaf();

export function splitPane(
  root: Pane,
  targetId: string,
  direction: Direction
): Pane {
  if (root.id === targetId && root.kind === "leaf") {
    return {
      kind: "split",
      id: nextId(),
      direction,
      ratio: 0.5,
      a: root,
      b: makeLeaf(),
    };
  }
  if (root.kind === "split") {
    return {
      ...root,
      a: splitPane(root.a, targetId, direction),
      b: splitPane(root.b, targetId, direction),
    };
  }
  return root;
}

export function removePane(root: Pane, targetId: string): Pane | null {
  if (root.id === targetId) return null;
  if (root.kind === "leaf") return root;

  if (root.a.id === targetId) return root.b;
  if (root.b.id === targetId) return root.a;

  const newA = removePane(root.a, targetId);
  const newB = removePane(root.b, targetId);
  if (newA === null) return newB;
  if (newB === null) return newA;
  return { ...root, a: newA, b: newB };
}

export function setRatio(root: Pane, targetId: string, ratio: number): Pane {
  if (root.kind === "leaf") return root;
  if (root.id === targetId) {
    return { ...root, ratio: clamp(ratio, 0.1, 0.9) };
  }
  return {
    ...root,
    a: setRatio(root.a, targetId, ratio),
    b: setRatio(root.b, targetId, ratio),
  };
}

export function setLeafCommand(
  root: Pane,
  targetId: string,
  command: string
): Pane {
  if (root.kind === "leaf") {
    if (root.id === targetId) return { ...root, command: command || undefined };
    return root;
  }
  return {
    ...root,
    a: setLeafCommand(root.a, targetId, command),
    b: setLeafCommand(root.b, targetId, command),
  };
}

export function findLeaf(root: Pane, targetId: string): Leaf | null {
  if (root.kind === "leaf") return root.id === targetId ? root : null;
  return findLeaf(root.a, targetId) ?? findLeaf(root.b, targetId);
}

export function countLeaves(root: Pane): number {
  if (root.kind === "leaf") return 1;
  return countLeaves(root.a) + countLeaves(root.b);
}

const clamp = (n: number, lo: number, hi: number) =>
  Math.max(lo, Math.min(hi, n));

/**
 * Emit a tmux shell script that recreates the given layout.
 *
 * Strategy: walk the tree DFS. Every leaf gets a stable creation index
 * (0 for the first pane, then 1, 2, ...). When we hit a split we emit
 * `select-pane -t session.<idx>` then `split-window -h|-v -l N%` which
 * creates the b-subtree rooted at the next index.
 */
export function generateScript(opts: {
  sessionName: string;
  tree: Pane;
  tmuxPath?: string;
}): string {
  const session = (opts.sessionName || "main").replace(/[^a-zA-Z0-9_-]/g, "_");
  const tmux = opts.tmuxPath || "tmux";

  const lines: string[] = [
    "#!/bin/sh",
    "# Generated by tmux-grid",
    `SESSION="${session}"`,
    `TMUX="${tmux}"`,
    "",
    `if "$TMUX" has-session -t "$SESSION" 2>/dev/null; then`,
    `  exec "$TMUX" attach -t "$SESSION"`,
    "fi",
    "",
    `"$TMUX" new-session -d -s "$SESSION"`,
  ];

  let next = 0;
  const idxForLeaf = new Map<string, number>();

  const walk = (node: Pane, currentIdx: number): void => {
    if (node.kind === "leaf") {
      idxForLeaf.set(node.id, currentIdx);
      return;
    }

    const flag = node.direction === "h" ? "-h" : "-v";
    const bPercent = Math.round((1 - node.ratio) * 100);
    next += 1;
    const newIdx = next;

    lines.push(`"$TMUX" select-pane -t "$SESSION.${currentIdx}"`);
    lines.push(
      `"$TMUX" split-window ${flag} -l ${bPercent}% -t "$SESSION.${currentIdx}"`
    );

    walk(node.a, currentIdx);
    walk(node.b, newIdx);
  };

  walk(opts.tree, 0);

  const commandLeaves: Array<[number, string]> = [];
  const collectCommands = (node: Pane) => {
    if (node.kind === "leaf") {
      if (node.command && node.command.trim()) {
        const idx = idxForLeaf.get(node.id);
        if (idx !== undefined) commandLeaves.push([idx, node.command.trim()]);
      }
      return;
    }
    collectCommands(node.a);
    collectCommands(node.b);
  };
  collectCommands(opts.tree);

  if (commandLeaves.length > 0) {
    lines.push("");
    for (const [idx, cmd] of commandLeaves) {
      const escaped = cmd.replace(/"/g, '\\"');
      lines.push(
        `"$TMUX" send-keys -t "$SESSION.${idx}" "${escaped}" C-m`
      );
    }
  }

  lines.push("");
  lines.push(`"$TMUX" select-pane -t "$SESSION.0"`);
  lines.push(`exec "$TMUX" attach -t "$SESSION"`);
  lines.push("");

  return lines.join("\n");
}
